CREATE TABLE IF NOT EXISTS Sensor (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE
);

INSERT INTO Sensor (name) VALUES ('Test sensor');

CREATE TABLE Measurement (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id INT REFERENCES Sensor(id),
    value FLOAT NOT NULL CHECK ( value >= -100 AND value <= 100 ),
    raining BOOLEAN NOT NULL,
    created_at TIMESTAMP
);

INSERT INTO Measurement (sensor_id, value, raining, created_at)
VALUES (1, 25.35, true, '2022-07-23'), (1, -18.84, false, '2023-02-12');